### ISSUE TITLE
Possibly build .deb package from sources

### ISSUE THREAD

**Issue by Phylex** [GuenterQuast/PhyPiDAQ#7]
Some things here look like they really don't belong there. The installibs folder being one of them. This looks like the whole thing should be put into a debian package. The thing with the installibs especially is that they are explicitly compiled for the the arm architecture and this is not particularly neccesary if using the debian package format the libs, independent of architecture can be specified.
If the package gets accepted by the raspbian people and put on an official mirror it makes installation much easier for the teachers and other school personal that operates the phypidaq. I'll start reading the requirements for .deb packages.

**Comment by GuenterQuast** [comment]
Postponed to new version !
